##### 1) Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [2]:
import numpy as np

a =np.arange(12,24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

##### 2) Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1

In [9]:
a1 = a.reshape(2, 6)
a2 = a.reshape(3, 4)
a3 = a.reshape(4, 3)
a4 = a.reshape(6, 2)
a5 = a.reshape(12, 1)
(a1, a2, a3, a4, a5)

(array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]),
 array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]),
 array([[12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23]]))

##### 3) Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [10]:
a_1 = a.reshape(-1, 6)
a_2 = a.reshape(-1, 4)
a_3 = a.reshape(4, -1)
a_4 = a.reshape(6, -1)
a_5 = a.reshape(12, -1)
(a_1, a_2, a_3, a_4, a_5)

(array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]),
 array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]),
 array([[12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23]]))

##### 4) Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [11]:
if len(a_5.shape) > 1:
    print('нет, нельзя')
else:
    print('да, можно')

нет, нельзя


##### 5) Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [110]:
rand_a = np.random.randn(3, 4)
rand_a

array([[-1.77978304,  0.21071379, -0.21506159,  0.88061405],
       [ 0.91651277,  0.62483582, -1.02704802,  0.06014511],
       [ 1.26557816, -0.91624632, -0.83901152,  0.67607518]])

In [111]:
#вопрос: почему rand_a.std() возвращает число отличное от 1, когда randn генерирует массив чисел
#со стандартным отклонением 1.
rand_a.std()

0.9093559116946947

In [112]:
rand_a_flat = rand_a.flatten()
rand_a_flat

array([-1.77978304,  0.21071379, -0.21506159,  0.88061405,  0.91651277,
        0.62483582, -1.02704802,  0.06014511,  1.26557816, -0.91624632,
       -0.83901152,  0.67607518])

##### 6) Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [114]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

##### 7) Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [118]:
b = np.arange(20, 1, -2).reshape(1, 10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

в отличие от массива a массив b является двумерным: 1 строка и 10 столбцов

##### 8) Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [4]:
a = np.zeros((2, 2))
b = np.ones((3, 2))
v = np.vstack((a,b))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [5]:
v.size

10

##### 9) Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [6]:
a = np.arange(0, 12)

In [7]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
A = a.reshape(4, 3)

In [10]:
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [11]:
At = A.T

In [12]:
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [13]:
B = A @ At

In [14]:
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [15]:
B.size

16

In [16]:
d = np.linalg.det(B)

In [17]:
d

0.0

обратную матрицу выислить невозможно так как определить матрицы B равен нулю

##### 10) Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [24]:
np.random.seed(42)

##### 11) Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно.

In [32]:
c = np.random.randint(0, 16, 16)

In [33]:
c

array([13, 14, 13,  2, 11,  6,  3, 15,  8,  2,  4,  2,  6,  4,  8,  6])

##### 12) Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [34]:
C = c.reshape(4,-1)

In [35]:
C

array([[13, 14, 13,  2],
       [11,  6,  3, 15],
       [ 8,  2,  4,  2],
       [ 6,  4,  8,  6]])

In [36]:
D = C * 10 + B

In [37]:
D

array([[135, 154, 153,  52],
       [124, 110, 116, 272],
       [103, 106, 189, 232],
       [ 92, 162, 292, 362]])

In [38]:
np.linalg.det(D)

-185817199.99999955

In [41]:
np.linalg.matrix_rank(D)

4

In [44]:
D_inv = np.linalg.inv(D)

In [46]:
D_inv

array([[-3.95980566e-04,  3.22897988e-06,  2.37983351e-02,
        -1.51975167e-02],
       [ 9.07041975e-03,  9.08613411e-03, -3.64048107e-02,
         1.52011762e-02],
       [-1.23852905e-03, -1.06993325e-02,  1.67565758e-02,
        -2.52183329e-03],
       [-2.95946769e-03,  4.56340963e-03, -3.27289401e-03,
         1.85623290e-03]])

##### 13) Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [48]:
D_inv[D_inv < 0], D_inv[D_inv > 0] = 0, 1

In [49]:
D_inv

array([[0., 1., 1., 0.],
       [1., 1., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 1.]])

In [66]:
E = np.where(D_inv == 1, B, C)

In [67]:
E

array([[ 13,  14,  23,   2],
       [ 14,  50,   3, 122],
       [  8,   2, 149,   2],
       [  6, 122,   8, 302]])